 rem code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension EditorConfig.EditorConfig
code --install-extension alefragnani.project-manager
code --install-extension bajdzis.vscode-database
code --install-extension daltonjorge.scala
code --install-extension dbankier.vscode-quick-select
code --install-extension deerawan.vscode-dash
code --install-extension eamodio.gitlens
code --install-extension erd0s.terraform-autocomplete
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension gabro.vscode-scalafmt
code --install-extension howardzuo.vscode-favorites
code --install-extension humao.rest-client
code --install-extension jakebathman.mysql-syntax
code --install-extension jblack.mysql-scratchpad
code --install-extension kaiwood.better-line-select
code --install-extension kirchner-trevor.shopify-liquid-preview
code --install-extension kken0201.vscode-esa
code --install-extension kkeri.luna
code --install-extension lightbend.vscode-sbt-scala
code --install-extension mauve.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension msysyamamoto.vscode-digdag
code --install-extension neilding.language-liquid
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.java
code --install-extension shuworks.vscode-table-formatter
code --install-extension sio-iago.restql-language
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension WallabyJs.quokka-vscode
code --install-extension yzhang.markdown-all-in-one